#!/usr/bin/env python3
"""Update refs.lock, the provenance record for the blessed references.

Writes one YAML block per sample: the payload hash, event and branch counts,
the converter commit, the stack versions, and the input files.

Usage:
  refs_lock.py --update ID --digest REF.json --key4hep REL [--lock refs.lock]
"""
import argparse, hashlib, json, os, subprocess, sys
from datetime import datetime, timezone
from pathlib import Path

import yaml


def payload_sha(digest):
    """SHA-256 over the digest's payload section, truncated to 32 characters."""
    blob = json.dumps(digest["payload"], sort_keys=True).encode()
    return hashlib.sha256(blob).hexdigest()[:32]


def converter_commit():
    """HEAD of the git checkout containing this script, or None.

    DELPHI_CI_COMMIT overrides the lookup.
    """
    if os.environ.get("DELPHI_CI_COMMIT"):
        return os.environ["DELPHI_CI_COMMIT"]
    here = str(Path(__file__).resolve().parent)
    try:
        return subprocess.check_output(["git", "-C", here, "rev-parse", "HEAD"],
                                       stderr=subprocess.DEVNULL, text=True).strip()
    except Exception:
        return None


def blessed_by():
    """Name recorded as having produced the reference."""
    return (os.environ.get("GITHUB_ACTOR")
            or os.environ.get("SUDO_USER") or os.environ.get("USER") or "unknown")


HEADER = """\
# Provenance for the blessed conversion-identity references.
# The reference files themselves live on the test machine under $DELPHI_CI_REFS.
# Generated by refs_lock.py; do not edit by hand.
"""


def update(lock, sample_id, d, key4hep, commit=None):
    """Replace one sample's block in the lock file. Returns its payload hash."""
    commit = commit or converter_commit()
    if commit is None:
        raise RuntimeError("cannot determine the converter commit - bless from a "
                           "git checkout, or set DELPHI_CI_COMMIT")
    lock = Path(lock)
    data = (yaml.safe_load(lock.read_text()) if lock.exists() else None) or {}
    data[sample_id] = {
        "payload_sha": payload_sha(d),
        "entries": d["payload"]["entries"],
        "branches": len(d["payload"]["branches"]),
        "converter_commit": commit,
        "key4hep": key4hep,
        "podio": d.get("stack", {}).get("podio"),
        "edm4hep": d.get("stack", {}).get("edm4hep"),
        "input": [{"name": f.get("name") or f["path"],   # relative to the data root
                   "size": f.get("size"), "sha256": f.get("sha256")}
                  for f in d.get("input", {}).get("files", [])],
        "blessed_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "blessed_by": blessed_by(),
    }
    lock.write_text(HEADER + yaml.safe_dump(data, sort_keys=True,
                                            default_flow_style=False))
    return data[sample_id]["payload_sha"]


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--update", required=True, metavar="ID", help="sample id")
    p.add_argument("--digest", required=True, help="the blessed reference digest")
    p.add_argument("--key4hep", required=True, help="key4hep release used")
    p.add_argument("--lock", default=str(Path(__file__).with_name("refs.lock")))
    a = p.parse_args()

    d = json.loads(Path(a.digest).read_text())
    try:
        sha = update(a.lock, a.update, d, a.key4hep)
    except RuntimeError as e:
        print(f"refs_lock: {e}", file=sys.stderr)
        return 1
    print(f"refs.lock: updated {a.update} ({sha})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
